### ISSUE TITLE
Install failed  while creating the image file

### ISSUE THREAD

**Issue by h4cd0c** [attacksurge/ax#15]
![Screenshot 2024-12-06 at 11 35 34 AM](https://github.com/user-attachments/assets/79104a62-f83f-4b3c-9952-eff0683ce6bf)

**Comment by h4cd0c** [comment]
i tried mutiple time with axiom build after few installation gets failed to create image

**Comment by 0xtavian** [comment]
@Jaikumar3 

Seems like go is not being installed. Can you show me the provisioner you are using? I’m guessing it’s custom? 

Edit: also check out the yellow text in ur screenshot. Delete any images on the account as well and try again. Or request a larger image size allocation by opening up a support ticket.

**Comment by h4cd0c** [comment]
@0xtavian Hi i used default provisioner only and i try large size too like 50 gb and 70gb .. still getting same error

**Comment by 0xtavian** [comment]
@Jaikumar3 ~looking at the screenshot above, it seems like its trying to also install aws cli which is not in any Provisioner.~

try deleting ~/.axiom and starting over. 

exit: OK its actually the reconftw provisioner that installs aws cli and fails to install nuclei v2. Will fix that as well.

**Comment by h4cd0c** [comment]
@0xtavian i used default provisioner..  try ~/.axiom folder too .. i tried more dan 10-times same error

**Comment by 0xtavian** [comment]
@Jaikumar3 
can you show me the rest of the axiom build terminal output? feel free to discuss in DM. join our discord https://discord.com/invite/c6BHVfn

**Comment by h4cd0c** [comment]
@0xtavian i attach the file full installtion of ax
[message.txt](https://github.com/user-attachments/files/18049231/message.txt)

**Comment by 0xtavian** [comment]
@Jaikumar3 Thanks, i'm able to confirm there is some issue with Linode whne using the default provisioner. I believe Linode changed something recently. 

However, even though I get the `002 context deadline exceeded` error, the image still builds successfully. 

A few minutes after you receive the error, can you run `ax images ls` to see if the image is in fact created?

You might need to select the image (`ax images select axiom-default-$timestamp`) since Packer reports the image creation failed, Ax wont automatically select it.

Thanks for reporting. Looking into it.
