### ISSUE TITLE
Is it possible to add `custom_vms`?

### ISSUE THREAD

**Issue by 0xhunster** [attacksurge/ax#9]
Is it possible to add custom VPS, for example `Custom VPS Addition!` from https://github.com/FleexSecurity/fleex/releases/tag/v2.0

**Comment by 0xtavian** [comment]
Hey @0xhunster,

You can customize the tools that get installed during the Packer image build process (`ax build`) by [Bringing Your Own Provisioner](https://ax.attacksurge.com/fundamentals/bring-your-own-provisioner). There are some configurations such as SSH port on 2266 and username `op` that are not easily changed since the various ax scripts rely on them. Lmk if that answers your question!

Feel free to join us on discord! https://discord.com/invite/c6BHVfn
